USE EVENTPRIME
GO

CREATE TABLE _user.users(
id BIGINT IDENTITY PRIMARY KEY NOT NULL,
email VARCHAR(50) NOT NULL ,
name VARCHAR(100) NOT NULL ,
password VARCHAR(100) NOT NULL,
role VARCHAR(15) NOT NULL,
CHECK(role in ('SUPERADMIN', 'ADMIN', 'CLIENT'))
)

CREATE TABLE _user.validation_tokens(
email VARCHAR(50) NOT NULL,
token VARCHAR(50) NOT NULL
)

CREATE TABLE _event.events(
id BIGINT IDENTITY PRIMARY KEY NOT NULL,
creatorid BIGINT FOREIGN KEY REFERENCES _user.users(id),
name VARCHAR(250)
)

ALTER TABLE _event.events 
ADD 
title VARCHAR(50) NOT NULL,
event_type SMALLINT NOT NULL,
event_category SMALLINT NOT NULL,
online_event BIT NOT NULL,
event_location VARCHAR(50) NOT NULL,
event_start_date DATE NOT NULL,
event_end_date DATE NOT NULL,
frequency SMALLINT NOT NULL

ALTER TABLE _event.events 
DROP COLUMN name

CREATE TABLE _event.tickets(
id BIGINT IDENTITY PRIMARY KEY NOT NULL,
name VARCHAR(60) NOT NULL,
eventid BIGINT FOREIGN KEY REFERENCES _event.events(id),
type VARCHAR(10) NOT NULL,
quantity INT NOT NULL,
price FLOAT NOT NULL
)

ALTER TABLE _event.tickets
ADD CHECK(type in ('FREE','PAID'));