USE EVENTPRIME
GO

CREATE TABLE _user.e_creator(
id BIGINT IDENTITY PRIMARY KEY NOT NULL,
email VARCHAR(50),
name VARCHAR(100),
password VARCHAR(50)
)

CREATE TABLE _event.events(
id BIGINT IDENTITY PRIMARY KEY NOT NULL,
creatorid BIGINT FOREIGN KEY REFERENCES _user.e_creator(id),
name VARCHAR(250)
)